# Generated by Django 2.2.2 on 2022-01-04 19:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ToDo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
