# Generated by Django 2.2.2 on 2022-01-04 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('ToDo', '0003_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
